#!/usr/bin/env python3
"""Render the per-genus character wiki (memory/CHARACTERS.md).

The actual stat derivation lives in pipeline/stats.py — this script just walks
the rows it returns and writes the Markdown. Editing balance / formulas? Edit
pipeline/stats.py and re-run both this AND seed_genera.py.
"""

from collections import defaultdict

from pipeline.stats import (
    CSV_DEFAULT, CHARDIR_DEFAULT, MIN_COUNT,
    collect_genus_data, compute_genus_rows,
)

OUT = "memory/CHARACTERS.md"


def main():
    rows = compute_genus_rows(CSV_DEFAULT, CHARDIR_DEFAULT)
    if not rows:
        print("No stat-blocked genera; aborting.")
        return

    p_med = rows[0]['archetype_median_power']
    a_med = rows[0]['archetype_median_agility']

    # Group rows by base archetype (strip legendary suffix) for section output.
    order = ["Bruiser — Elite Carry", "Juggernaut — Tank/Artillery",
             "Skirmisher — Glass Cannon", "Support — Chaff/Filler"]
    groups = defaultdict(list)
    for r in rows:
        base = r['archetype'].replace(" (Legendary)", "")
        groups[base].append(r)

    blurbs = {
        "Bruiser — Elite Carry": "High power AND high agility: strong, durable, "
            "and quick. The carnage units.",
        "Juggernaut — Tank/Artillery": "High power, low agility: hard-hitting, "
            "tanky, long-range, but slow to move and strike. Walls & artillery.",
        "Skirmisher — Glass Cannon": "Low power, high agility: fast strikes and "
            "movement, fragile and short-range. Swarmers.",
        "Support — Chaff/Filler": "Low power and low agility: weak filler that "
            "wins by sheer numbers in tree-dense ZIP codes.",
    }

    with open(OUT, 'w') as f:
        f.write("# Characters — Boomoorlog Genus Roster\n\n")
        f.write("Auto-generated by `generate_characters.py`. One row per genus "
                f"(count >= {MIN_COUNT}). Stats normalized 1-10; **Power** = mean "
                "stat x world-rarity multiplier.\n\n")
        f.write("Stat sources (see `STATS.md`): **Attack**=wood hardness (research), "
                "**Range**=local height (data), **HP**=mass (data) + longevity "
                "(research), **A.Spd**=inverse wood hardness (research), "
                "**Move**=growth vigor (data). Per-genus research in "
                "`memory/characters/`.\n\n")
        f.write(f"Archetype split uses medians: power-axis={p_med:.1f}, "
                f"agility-axis={a_med:.1f}.\n\n")

        f.write("## All characters (by Power)\n\n")
        f.write("| Genus | Common | NL | Trees | Atk | Rng | HP | A.Spd | Move | Rarity | Power | Archetype |\n")
        f.write("|---|---|---|--:|--:|--:|--:|--:|--:|:--|--:|---|\n")
        for r in rows:
            f.write(f"| *{r['slug']}* | {r['common_name']} | {r['dutch_name']} | "
                    f"{r['tree_count']} | {r['attack']} | {r['range']} | {r['health']} | "
                    f"{r['attack_speed']} | {r['move_speed']} | {r['world_rarity_label']} | "
                    f"{r['power_score']} | {r['archetype']} |\n")

        f.write("\n## Archetypes (TD stat builds)\n\n")
        for name in order:
            grp = groups.get(name)
            if not grp:
                continue
            f.write(f"### {name}\n{blurbs[name]}\n\n")
            for r in sorted(grp, key=lambda x: -x['power_score']):
                star = "★" if r['world_rarity_multiplier'] >= 1.25 else ""
                f.write(f"- **{r['slug']}** ({r['common_name']}){star} — {r['personality']}\n")
            f.write("\n")

        f.write("★ = Legendary (world rarity = rare, multiplier 1.25).\n\n")
        f.write("## Long tail\n\n")
        cnt, _, _, _, _ = collect_genus_data(CSV_DEFAULT)
        tail = sorted((g for g in cnt if cnt[g] < MIN_COUNT), key=lambda g: -cnt[g])
        f.write(f"{len(tail)} more genera have <{MIN_COUNT} Amsterdam trees and are "
                "not stat-blocked here. Globally-rare giants among them (e.g. "
                "Sequoiadendron, Sequoia, Araucaria, Davidia) are prime **Legendary** "
                "cards when they appear in a ZIP code.\n")

    print(f"Wrote {OUT} with {len(rows)} genera.")
    print("Archetype counts: " +
          ", ".join(f"{k.split(' ')[0]}={len(v)}" for k, v in groups.items()))


if __name__ == "__main__":
    main()
