#!/usr/bin/env python3
"""Seed the `creatures` table in Supabase from data/creatures.csv.

The CSV is regenerated by extract_creatures.py from memory/characters/*.md.
This script:
  1. Reads data/creatures.csv.
  2. UPSERTs every row into `creatures` (slug is the PK).

Env: requires SUPABASE_DB_URL in .env at the repo root (same as seed_genera).
"""

import csv
import sys
from pathlib import Path

import psycopg2
from psycopg2.extras import execute_values

REPO = Path(__file__).resolve().parents[1]
CSV_PATH = REPO / "data" / "creatures.csv"


def load_env(path: Path = REPO / ".env") -> dict:
    env = {}
    with path.open() as f:
        for raw in f:
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, _, v = line.partition("=")
            env[k.strip()] = v.strip()
    return env


def load_rows():
    rows = []
    with CSV_PATH.open() as f:
        for r in csv.DictReader(f):
            tree_genera = [g for g in r["tree_genera"].split(";") if g]
            rows.append((
                r["slug"],
                r["common_name"],
                r["latin_name"] or None,
                r["pic_file"] or None,
                int(r["tree_count"]),
                tree_genera,
            ))
    return rows


UPSERT = """
INSERT INTO creatures (slug, common_name, latin_name, pic_file, tree_count, tree_genera)
VALUES %s
ON CONFLICT (slug) DO UPDATE SET
    common_name = EXCLUDED.common_name,
    latin_name  = EXCLUDED.latin_name,
    pic_file    = EXCLUDED.pic_file,
    tree_count  = EXCLUDED.tree_count,
    tree_genera = EXCLUDED.tree_genera
"""


def main() -> None:
    env = load_env()
    db_url = env.get("SUPABASE_DB_URL")
    if not db_url:
        sys.exit("SUPABASE_DB_URL missing from .env")

    rows = load_rows()
    print(f"Prepared {len(rows)} creatures from {CSV_PATH.relative_to(REPO)}.")

    with psycopg2.connect(db_url) as conn:
        with conn.cursor() as cur:
            execute_values(cur, UPSERT, rows)
            cur.execute("SELECT COUNT(*) FROM creatures")
            n = cur.fetchone()[0]
        conn.commit()
    print(f"creatures table now has {n} rows.")


if __name__ == "__main__":
    main()
